Publish things under the new name (gel-server, gel-cli, gel-ls)
Original package definitions remain unchanged so that back branches can
continue to be built and published as `edgedb`.  .deb and .rpm platforms
publish "transitional" packages with old names which pull the new-named
package as the dependency.

diff --git a/integration/linux/testpublished/centos-8/Dockerfile b/integration/linux/testpublished/centos-8/Dockerfile
--- a/integration/linux/testpublished/centos-8/Dockerfile
+++ b/integration/linux/testpublished/centos-8/Dockerfile
@@ -38,10 +38,23 @@ while [ $try -le 30 ]; do\n\
     sleep 30\n\
 done\n\
 \n\
-if [ "${PKG_NAME}" == "edgedb-cli" ]; then\n\
+if [ "${PKG_NAME}" == "gel-cli" ]; then\n\
+    gel --help\n\
+    gel --version\n\
+elif [ "${PKG_NAME}" == "edgedb-cli" ]; then\n\
     edgedb --help\n\
     edgedb --version\n\
-else\n\
+elif [ "${PKG_NAME}" == "gel-server" ]; then\n\
+    slot="${PKG_VERSION_SLOT}"\n\
+\n\
+    if [ -z "${slot}" ]; then\n\
+        echo ::error "Cannot determine package version slot."\n\
+        exit 1\n\
+    fi\n\
+\n\
+    gel-server-${slot} --help\n\
+    gel-server-${slot} --version\n\
+elif [ "${PKG_NAME}" == "edgedb-server" ]; then\n\
     slot="${PKG_VERSION_SLOT}"\n\
 \n\
     if [ -z "${slot}" ]; then\n\
