Adjustments for metapkg artifact packaging revamp
All targets now produce build artifacts as tarballs with JSON metadata.

diff --git a/integration/linux/test/centos-7/Dockerfile b/integration/linux/test/centos-7/Dockerfile
--- a/integration/linux/test/centos-7/Dockerfile
+++ b/integration/linux/test/centos-7/Dockerfile
@@ -17,9 +17,6 @@ if [ -n "${PKG_PLATFORM_VERSION}" ]; then\n\
     dest+="-${PKG_PLATFORM_VERSION}"\n\
 fi\n\
 \n\
-re="edgedb-server-([[:digit:]]+(-(alpha|beta|rc)[[:digit:]]+)?(-dev[[:digit:]]+)?).*\\.rpm"\n\
-slot="$(ls ${dest} | sed -n -E "s/${re}/\\1/p")"\n\
-\n\
 dist='\''el$releasever'\''\n\
 if [ -n "${PKG_SUBDIST}" ]; then\n\
     dist+=".${PKG_SUBDIST}"\n\
@@ -36,13 +33,41 @@ EOF\n\
 \n\
 try=1\n\
 while [ $try -le 30 ]; do\n\
-    yum makecache && yum install --verbose -y edgedb-cli && break || true\n\
+    yum makecache && yum install --verbose -y edgedb-cli jq && break || true\n\
     try=$(( $try + 1 ))\n\
     echo "Retrying in 10 seconds (try #${try})"\n\
     sleep 10\n\
 done\n\
 \n\
-yum install -y "${dest}"/edgedb-server-${slot}*.x86_64.rpm\n\
+slot=\n\
+rpm=\n\
+for pack in ${dest}/*.tar; do\n\
+    if [ -e "${pack}" ]; then\n\
+        slot=$(tar -xOf "${pack}" "build-metadata.json" \\\n\
+               | jq -r ".version_slot")\n\
+        rpm=$(tar -xOf "${pack}" "build-metadata.json" \\\n\
+              | jq -r ".contents | keys[]" \\\n\
+              | grep "^edgedb-server.*\\.rpm$")\n\
+        if [ -n "${rpm}" ]; then\n\
+            break\n\
+        fi\n\
+    fi\n\
+done\n\
+\n\
+if [ -z "${rpm}" ]; then\n\
+    echo "${dest} does not seem to contain an edgedb-server .rpm" >&2\n\
+    exit 1\n\
+fi\n\
+\n\
+if [ -z "${slot}" ]; then\n\
+    echo "could not determine version slot from build metadata" >&2\n\
+    exit 1\n\
+fi\n\
+\n\
+tmpdir=$(mktemp -d)\n\
+tar -x -C "${tmpdir}" -f "${pack}" "${rpm}"\n\
+yum install -y "${tmpdir}/${rpm}"\n\
+rm -rf "${tmpdir}"\n\
 \n\
 if [ "$1" == "bash" ]; then\n\
     echo su edgedb -c \\\n\
