Add support for Github workflow
This adds the actions necessary to perform EdgeDB builds in Github.
The setup mostly mirrors the Gitlab-based flow with a couple of
Github-specific actions.

diff --git a/integration/containers/testpublished/centos-7/Dockerfile b/integration/containers/testpublished/centos-7/Dockerfile
--- a/integration/containers/testpublished/centos-7/Dockerfile
+++ b/integration/containers/testpublished/centos-7/Dockerfile
@@ -5,3 +5,33 @@
 #
 
 FROM centos:7
+RUN /bin/echo -e '#!/bin/bash\n\
+\n\
+set -ex\n\
+\n\
+slot="${PKG_VERSION_SLOT}"\n\
+\n\
+if [ -z "${slot}" ]; then\n\
+    echo ::error "Cannot determine package version slot."\n\
+    exit 1\n\
+fi\n\
+\n\
+dist='\''el\\$releasever'\''\n\
+if [ -n "${PKG_SUBDIST}" ]; then\n\
+    dist+=".${PKG_SUBDIST}"\n\
+fi\n\
+\n\
+cat <<EOF >/etc/yum.repos.d/edgedb.repo\n\
+[edgedb]\n\
+name=edgedb\n\
+baseurl=https://packages.edgedb.com/rpm/${dist}/\n\
+enabled=1\n\
+gpgcheck=1\n\
+gpgkey=https://packages.edgedb.com/keys/edgedb.asc\n\
+EOF\n\
+\n\
+yum install -y edgedb-${slot}\n\
+edgedb --help\n\' >/entrypoint.sh
+
+RUN chmod +x /entrypoint.sh
+ENTRYPOINT ["/entrypoint.sh"]
diff --git a/integration/containers/testpublished/ubuntu-bionic/Dockerfile b/integration/containers/testpublished/ubuntu-bionic/Dockerfile
--- a/integration/containers/testpublished/ubuntu-bionic/Dockerfile
+++ b/integration/containers/testpublished/ubuntu-bionic/Dockerfile
@@ -5,3 +5,32 @@
 #
 
 FROM ubuntu:bionic
+RUN /bin/echo -e '#!/bin/bash\n\
+\n\
+set -ex\n\
+\n\
+export DEBIAN_FRONTEND=noninteractive\n\
+\n\
+slot="${PKG_VERSION_SLOT}"\n\
+\n\
+if [ -z "${slot}" ]; then\n\
+    echo ::error "Cannot determine package version slot."\n\
+    exit 1\n\
+fi\n\
+\n\
+dist="${PKG_PLATFORM_VERSION}"\n\
+if [ -n "${PKG_SUBDIST}" ]; then\n\
+    dist+=".${PKG_SUBDIST}"\n\
+fi\n\
+\n\
+apt-get update\n\
+apt-get install -y curl gnupg apt-transport-https\n\
+curl https://packages.edgedb.com/keys/edgedb.asc | apt-key add -\n\
+echo deb [arch=amd64] https://packages.edgedb.com/apt ${dist} main \\\n\
+    >> /etc/apt/sources.list.d/edgedb.list\n\
+apt-get update\n\
+apt-get install -y edgedb-${slot}\n\
+edgedb --help\n\' >/entrypoint.sh
+
+RUN chmod +x /entrypoint.sh
+ENTRYPOINT ["/entrypoint.sh"]
