integration: Drop Debian 9, Ubuntu 16.04, add Debian 12 and RockyLinux 9

diff --git a/integration/linux/test-systemd/fedora-29/Dockerfile b/integration/linux/test-systemd/fedora-29/Dockerfile
--- a/integration/linux/test-systemd/fedora-29/Dockerfile
+++ b/integration/linux/test-systemd/fedora-29/Dockerfile
@@ -27,6 +27,16 @@ function finish() {\n\
 \n\
 trap finish 0\n\
 \n\
+try=1\n\
+while [ $try -le 30 ]; do\n\
+    yum makecache \\\n\
+    && yum install --enablerepo=edgedb,edgedb-nightly --verbose -y edgedb-cli \\\n\
+    && break || true\n\
+    try=$(( $try + 1 ))\n\
+    echo "Retrying in 10 seconds (try #${try})"\n\
+    sleep 10\n\
+done\n\
+\n\
 dest="artifacts"\n\
 if [ -n "${PKG_PLATFORM}" ]; then\n\
     dest+="/${PKG_PLATFORM}"\n\
@@ -35,26 +45,48 @@ if [ -n "${PKG_PLATFORM_VERSION}" ]; then\n\
     dest+="-${PKG_PLATFORM_VERSION}"\n\
 fi\n\
 \n\
-re="edgedb-server-([[:digit:]]+(-(alpha|beta|rc)[[:digit:]]+)?(-dev[[:digit:]]+)?).*\\.rpm"\n\
-slot="$(ls ${dest} | sed -n -E "s/${re}/\\1/p")"\n\
 \n\
-yum install -y "${dest}"/edgedb-server-${slot}*.x86_64.rpm\n\
+slot=\n\
+rpm=\n\
+for pack in ${dest}/*.tar; do\n\
+    if [ -e "${pack}" ]; then\n\
+        slot=$(tar -xOf "${pack}" "build-metadata.json" \\\n\
+               | jq -r ".version_slot")\n\
+        rpm=$(tar -xOf "${pack}" "build-metadata.json" \\\n\
+              | jq -r ".contents | keys[]" \\\n\
+              | grep "^edgedb-server.*\\.rpm$")\n\
+        if [ -n "${rpm}" ]; then\n\
+            break\n\
+        fi\n\
+    fi\n\
+done\n\
+\n\
+if [ -z "${rpm}" ]; then\n\
+    echo "${dest} does not seem to contain an edgedb-server .rpm" >&2\n\
+    exit 1\n\
+fi\n\
+\n\
+if [ -z "${slot}" ]; then\n\
+    echo "could not determine version slot from build metadata" >&2\n\
+    exit 1\n\
+fi\n\
+\n\
+tmpdir=$(mktemp -d)\n\
+tar -x -C "${tmpdir}" -f "${pack}" "${rpm}"\n\
+yum install -y "${tmpdir}/${rpm}"\n\
+rm -rf "${tmpdir}"\n\
 \n\
 systemctl enable --now edgedb-server-${slot} \\\n\
     || (journalctl -u edgedb-server-${slot} && exit 1)\n\
 \n\
-python="/usr/lib64/edgedb-server-${slot}/bin/python3"\n\
-edbcli="${python} -m edb.cli"\n\
-\n\
-su edgedb -c "${edbcli} --admin configure insert Auth \\\n\
-                --method=Trust --priority=0"\n\
-[[ "$(echo '\''SELECT 1 + 3;'\'' | ${edbcli} -u edgedb)" == *4* ]] || exit 1\n\
+[[ "$(edgedb --admin -u edgedb query '\''select 1 + 3'\'')" == *4* ]] || exit 1\n\
 echo "Success!"\n\
 \n\
 EOF\n\
 \n\
 chmod +x /usr/local/bin/script.sh\n\
 \n\
+mkdir -p /etc/systemd/system\n\
 cat >/etc/systemd/system/script.service <<EOF\n\
 [Unit]\n\
 Description=Main Script\n\
